basePath: /
consumes:
- application/x-www-form-urlencoded
definitions:
  Task:
    properties:
      description:
        type: string
        x-go-name: Description
      gid:
        type: string
        x-go-name: Gid
      id:
        format: int64
        type: integer
        x-go-name: Id
      task_column_id:
        format: int64
        type: integer
        x-go-name: TaskColumnId
      title:
        type: string
        x-go-name: Title
    type: object
    x-go-package: organizr/server/types
  TaskColumn:
    properties:
      board_id:
        format: int64
        type: integer
        x-go-name: BoardId
      gid:
        type: string
        x-go-name: Gid
      id:
        format: int64
        type: integer
        x-go-name: Id
      title:
        type: string
        x-go-name: Title
    type: object
    x-go-package: organizr/server/types
host: localhost:1323
info:
  description: API Documentation.
  title: Organizr
  version: 1.0.0
paths:
  /api/column/{Board_GID}:
    get:
      description: Retrieves all columns by parent board UUID
      operationId: retrieve-all
      responses:
        "200":
          $ref: '#/responses/multi-column-response'
        "400":
          $ref: '#/responses/error-response'
      tags:
      - column
    post:
      description: Creates a column in the board specified by UUID
      operationId: create
      responses:
        "200":
          $ref: '#/responses/single-column-response'
        "400":
          $ref: '#/responses/error-response'
      tags:
      - column
  /api/column/{Board_GID}/{Column_GID}:
    delete:
      description: Deletes column by parent board and column UUIDs
      operationId: delete
      responses:
        "200":
          description: ""
        "400":
          $ref: '#/responses/error-response'
      tags:
      - column
    get:
      description: Retrieves column by parent board and column UUIDs
      operationId: retrieve-one
      responses:
        "200":
          $ref: '#/responses/single-column-response'
        "400":
          $ref: '#/responses/error-response'
      tags:
      - column
    put:
      description: Updates column by parent board and column UUIDs
      operationId: update
      responses:
        "200":
          $ref: '#/responses/single-column-response'
        "400":
          $ref: '#/responses/error-response'
      tags:
      - column
  /api/login:
    post:
      description: Authenticates a member with their username and password from a
        POST, returning a new JWT session token
      operationId: login
      parameters:
      - example: user@email.com
        in: formData
        name: Username
        required: true
        type: string
      - example: password1234
        in: formData
        name: Password
        required: true
        type: string
      responses:
        "200":
          $ref: '#/responses/login-response'
        "400":
          $ref: '#/responses/error-response'
      tags:
      - authentication
  /api/register:
    post:
      description: Registers a new member using the supplied username, email, and
        password
      operationId: register
      parameters:
      - example: andrew
        in: formData
        name: Username
        required: true
        type: string
      - example: user@email.com
        in: formData
        name: Email
        required: true
        type: string
      - example: password1234
        in: formData
        name: Password
        required: true
        type: string
      responses:
        "200":
          description: ""
        "400":
          $ref: '#/responses/error-response'
      tags:
      - authentication
  /api/task/{Column_GID}:
    get:
      description: Retrieves all tasks by parent column UUID
      operationId: retrieve-all
      responses:
        "200":
          $ref: '#/responses/multi-task-response'
        "400":
          $ref: '#/responses/error-response'
      tags:
      - task
    post:
      description: Creates a task in the column specified by UUID
      operationId: create
      responses:
        "200":
          $ref: '#/responses/single-task-response'
        "400":
          $ref: '#/responses/error-response'
      tags:
      - task
  /api/task/{Column_GID}/{Task_GID}:
    delete:
      description: Deletes task by parent column and task UUIDs
      operationId: delete
      responses:
        "200":
          description: ""
        "400":
          $ref: '#/responses/error-response'
      tags:
      - task
    get:
      description: Retrieves task by parent column and task UUIDs
      operationId: retrieve-one
      responses:
        "200":
          $ref: '#/responses/single-task-response'
        "400":
          $ref: '#/responses/error-response'
      tags:
      - task
    put:
      description: Updates task by parent column and task UUIDs
      operationId: update
      responses:
        "200":
          $ref: '#/responses/single-task-response'
        "400":
          $ref: '#/responses/error-response'
      tags:
      - task
produces:
- application/json
responses:
  error-response:
    description: Error Response
    headers:
      Data: {}
    schema:
      properties:
        code:
          description: 'in: body'
          example: login_failed
          type: string
          x-go-name: Code
        message:
          description: 'in: body'
          example: Username and/or password are incorrect
          type: string
          x-go-name: Message
      type: object
  login-response:
    description: Authentication Response
    headers:
      Data: {}
    schema:
      properties:
        jwt:
          description: 'in: body'
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
          type: string
          x-go-name: JWT
      type: object
  multi-column-response:
    description: ""
    schema:
      items:
        $ref: '#/definitions/TaskColumn'
      type: array
  multi-task-response:
    description: ""
    schema:
      items:
        $ref: '#/definitions/Task'
      type: array
  single-column-response:
    description: ""
    schema:
      $ref: '#/definitions/TaskColumn'
  single-task-response:
    description: ""
    schema:
      $ref: '#/definitions/Task'
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
