basePath: /
consumes:
- application/x-www-form-urlencoded
host: localhost:1323
info:
  description: API Documentation.
  title: Organizr
  version: 1.0.0
paths:
  /api/login:
    post:
      description: Authenticates a member with their username and password from a
        POST, returning a new JWT session token
      operationId: login
      parameters:
      - example: user@email.com
        in: formData
        name: Username
        required: true
        type: string
      - example: password1234
        in: formData
        name: Password
        required: true
        type: string
      responses:
        "200":
          $ref: '#/responses/login-response'
        "400":
          $ref: '#/responses/error-response'
      tags:
      - authentication
  /api/register:
    post:
      description: Registers a new member using the supplied username, email, and
        password
      operationId: register
      parameters:
      - example: andrew
        in: formData
        name: Username
        required: true
        type: string
      - example: user@email.com
        in: formData
        name: Email
        required: true
        type: string
      - example: password1234
        in: formData
        name: Password
        required: true
        type: string
      responses:
        "200":
          description: ""
        "400":
          $ref: '#/responses/error-response'
      tags:
      - authentication
produces:
- application/json
responses:
  error-response:
    description: Error Response
  login-response:
    description: Authentication Response
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
